.gradle
/local.properties
/.idea/workspace.xml
/.idea/libraries
.idea/gradle.xml
.idea/modules.xml
.DS_Store
/build
/captures
app.iml
app/app.iml
*.iml
.idea
.settings
.project

# built application files
*.apk
*.ap_

# built native files
*.o
*.so

# files for the dex VM
*.dex

# Java class files
*.class
.classpath

# generated files
bin/
gen/

# Ignore gradle files
.gradle/
build/
gradle/

# Local configuration file (sdk path, etc)
local.properties

# Proguard folder generated by Eclipse
proguard/

project.properties
lint.xml
gradlew
gradlew.bat 